# Generated by Django 5.2.4 on 2025-09-23 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_orden', models.BigIntegerField(blank=True, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('hora_registro', models.TimeField(blank=True, db_index=True, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('latitud', models.DecimalField(blank=True, db_index=True, decimal_places=10, max_digits=12, null=True)),
                ('longitud', models.DecimalField(blank=True, db_index=True, decimal_places=10, max_digits=13, null=True)),
                ('zona', models.CharField(blank=True, max_length=20, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('canton', models.CharField(blank=True, max_length=100, null=True)),
                ('distrito', models.CharField(blank=True, max_length=100, null=True)),
                ('circuito', models.CharField(blank=True, max_length=100, null=True)),
                ('subcircuito', models.CharField(blank=True, max_length=100, null=True)),
                ('parroquia', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_delito', models.TextField(blank=True, null=True)),
                ('subtipo_delito', models.TextField(blank=True, null=True)),
                ('delito_dnpj', models.TextField(blank=True, null=True)),
                ('codigo_penal', models.TextField(blank=True, null=True)),
                ('modalidad', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'detalle',
            },
        ),
    ]
